### ISSUE TITLE
KeyboardInterrupt impossible

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#2]
Both test_network_receiver.py and test_network_sender.py can't be terminated by Strg+C. I get the following output.

^CTraceback (most recent call last):
  File "test_network_sender.py", line 43, in <module>
    time.sleep(0.1)
KeyboardInterrupt

**Comment by littleskunk** [comment]
Retest passed.

**Comment by littleskunk** [comment]
The new version ignores STRG+C (tested with windows executable)

'Did not received reply for msg id GOxmL76qkPWEWnvNiz/3GEII8fU= within 5 seconds
'
Traceback (most recent call last):
  File "storjnode", line 109, in <module>
KeyboardInterrupt
'Did not received reply for msg id nTt17jC+/hXnXvta2QHY3dfRA4U= within 5 seconds

**Comment by super3** [comment]
@F483 @littleskunk Updates on this one? This bug makes it hard to play around and debug.

**Comment by F483** [comment]
Still valid with new implementation, I know how to do this properly so I will take it.

**Comment by F483** [comment]
Two make sure twisted runs/stops properly two things need to be done on startup:

 * Run twisted via crochet
 * Remove the twisted SIGINT handler

This as been done in all examples and scripts using storjnode.

```
import signal                                                                                                   
from crochet import setup                                                                                       
                                                                                                        
# start twisted via crochet and remove twisted handler                           
setup()                                                                                                         
signal.signal(signal.SIGINT, signal.default_int_handler)
```
