### ISSUE TITLE
Package 0.0.11 release

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/storjnode#20]
See https://github.com/Storj/dataserv-client/issues/176

**Comment by super3** [comment]
@littleskunk Can you create this, and I'll release it?

**Comment by gordonwritescode** [comment]
This may be unnecessary - looks like dataserv-client refs 0.0.18 --> https://github.com/Storj/dataserv-client/blob/master/requirements.txt#L7 

Perhaps driveshare-gui needs to use the latest dataserv-client instead?

**Comment by littleskunk** [comment]
We are mixing different bugs now.

As soon as we hit the release button for the driveshare-client binary version 2.1.11 it will be available for driveshare-gui (Windows and Mac). The driveshare-client binary includes storjnode but as far as i remember it was a newer version and not 0.0.11. https://github.com/Storj/driveshare-gui/issues/46

For pypi follow the install introduction and use python2 and not python3. https://github.com/Storj/dataserv-client/issues/176.

Version 0.0.18 is released https://pypi.python.org/pypi/storjnode/0.0.18.

We dont need to release a new storjnode version or a storjnode binary.
