### ISSUE TITLE
loglevel info

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#22]
At the moment the loglevel is set to warning. https://github.com/Storj/storjnode/blob/develop/storjnode/log.py#L14

Dataserv-client needs loglevel info. Is it possible to add different loghandler? A spam log for twisted with loglevel warning and for dataserv-client loglevel info?

I found this: https://docs.python.org/2/howto/logging-cookbook.html

**Comment by F483** [comment]
Silenced twisted and set default log level to info.


https://github.com/Storj/storjnode/commit/6134cad3e9059034a9f88eacefb67a97dccaee90
