### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by robertsdotpm** [Storj/storjnode#24]
* Format everything with PEP8
* Investigate whether the serialization code can be made simpler based on relay_message doing it
* Change asserts in tests to assertTrue
* Re-factor code from file transfer client
* Add log messages to test_bandwidth instead of print statements

**Comment by F483** [comment]
I PEP8 formatted everything. The travis [config](https://github.com/Storj/storjnode/blob/develop/.travis.yml) is now more strict and will fail on pep8 violation as well as low coverage.

**Comment by robertsdotpm** [comment]
Thanks, I noticed you also did the assert thing and refactored some other stuff.
