### ISSUE TITLE
Fix ordered dict code!

### ISSUE THREAD

**Issue by robertsdotpm** [Storj/storjnode#25]
Passing a dict into OrderedDict makes no sense and leads to inconsistent results when encoding + decoding. Convert code to use tuples + lists to represent data, that way the order will always be consistent.

**Comment by F483** [comment]
I have replaced all dicts with ordered [(key, value)] lists.

Everything seems to be working again excepto for https://github.com/Storj/storjnode/blob/develop/tests/network/queued_file_transfer.py#L149 which my be unrelated.
