### ISSUE TITLE
Remove direct messages?

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#31]
Since direct messages cannot traverse NAT the have little or better no know usage. For simplicity and reducing amount of code/spec to maintain they should be remove if there is no pressing reason to leave them in.

**Comment by robertsdotpm** [comment]
Easy enough to fix but it seems like a lot of critical tests in node.py depend on this

**Comment by F483** [comment]
Yes but its bloat we cant really use because of NAT. So if anything critical depends on it, it should be changed.

**Comment by super3** [comment]
So sounds like we need to sit down and talk about this one. When it becomes more important we will just cover it in a sync meeting.

**Comment by F483** [comment]
With the most recent release it has become clear that the vast majority of nodes are behind a NAT. This means direct messages are useless for any practical purpose and anything that depends on them should be changed to work with relay messages.

Additionally if we only use relay messages we can rename the rpc call to 'msg' from 'relay_message' which reduces the overhead for every message by 10 bytes (which is significant for UDP pack ates).

![network map 2015-12-11 16 56 15 194054](https://cloud.githubusercontent.com/assets/977605/11749021/9cf5d242-a02b-11e5-81d6-9bd6a5b188db.jpg)

**Comment by F483** [comment]
Removed dircect messages and modified the api accordingly.
