### ISSUE TITLE
Unicode issues with DHT

### ISSUE THREAD

**Issue by robertsdotpm** [Storj/storjnode#32]
The DHT blindly accepts and prints unicode characters in the debug log which can mess up certain terminal programs. We need to either restrict this to ASCII and/or disallow printing unicode from user input to the debug log.

**Comment by F483** [comment]
The DHT accepts anything that can be encoded via http://msgpack.org/. This includes binary data, which I assume is messing up the log.

Nothing should just blindly print it to the log, do you have an example of what does so?

**Comment by robertsdotpm** [comment]
The store message requests print out the key name and the value (which can be unicode.)

**Comment by robertsdotpm** [comment]
https://github.com/F483/kademlia/pull/1  fixes this by converting unprintable binary to hex for key value pairs
