### ISSUE TITLE
Missing timeout for Received synack

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#4]
root@Develop:/home/storjnode/storjnode/bin# python test_network_sender.py [my address] [your address] test_network_sender.py
INFO storjnode.network.service 97: Starting network service!
INFO storjnode.network.service 125: Connecting to irc.quakenet.org:6667 as XLrgkBEbLDMB.
INFO storjnode.network.service 128: Connection established!
INFO storjnode.network.service 148: Joined own channel #18X6bmEjAKfAhqega9xmBgJfy4rrJ3zxth
INFO storjnode.network.service 103: Network service started!
INFO storjnode.network.service 475: Queued 1287bytes to send 16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
INFO storjnode.network.service 313: Requesting connection to node 16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
INFO storjnode.network.service 334: Sending syn to node channel #16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG
INFO storjnode.network.service 148: Joined own channel #18X6bmEjAKfAhqega9xmBgJfy4rrJ3zxth

The last line comes from a second terminal starting test_network_receiver.py. Sending syn to node channel #16ZcxFDdkVJR1P8GMNmWFyhS4EKrRMsWNG was the last message. I would expect a timeout or something like that.

**Comment by F483** [comment]
Timeouts are missing for pretty much everything and need to be added.

**Comment by F483** [comment]
Added timeouts.
