### ISSUE TITLE
Network monitor for Test Group C

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#41]
Add a network monitor that that records the following information for its x nearest neighbours.

 * Node peers
 * Storage (used, total, free)
 * Network ((ip, port), is_public)
 * Version (protocol, storjnode)
 * Bandwith (send, receive)
 * Latency (info relay, peers relay, setup transfer, p2p tcpip ping)

It only records this information for the x nearest neighbours as doing it fore the entire network is impractical. x much be chosen so that it is greater then k (number of neighbours in the routing table) to ensure neighbours not in the nodes routing table are also tested.

Another metric could be chosen as to which nodes to tests, but the nearest should be good as it will ensure the entire network is covered and its fairly random (as the node ids are random and you cant choose your neighbours).

For each time the node collects this information it should be saved in a shard on the node and the shard id published on the DHT with a predicable key `nodeid + i -> shardid` where `i` is an incrementing number starting a 0. This will allow a crawler looking for the statistics to find them easily.

CC @super3

**Comment by robertsdotpm** [comment]
Might also be useful to include whether auto forwarding works with UPnP or NATPMP + the type of NAT the router has (for determining if hole punching will work.) Then we'll know if the connection design will be satisfactory or not.
