### ISSUE TITLE
Improve network performance by decreasing twisted thread load

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#47]
Re-factor code so as little as possible is done in the twisted thread (of which there is only one).

This should significantly decrease build time and improve performance in general.

**Comment by F483** [comment]
Decreased it to a minimal (only relay messages are forwarded in the twisted thread).

**Comment by robertsdotpm** [comment]
@f483 another piece of code that is unnecessarily increasing twisted load is the download / upload processing loop. I can schedule that to occur outside the Twisted thread if you like?

        d = LoopingCall(
            process_transfers,
            self._data_transfer
        ).start(0.002, now=True)
