### ISSUE TITLE
Incorrect WAN IP listed in test output

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#49]
In the log output of the unit tests I see the following. Obviously 8.8.8.8 is the google DNS and not the WAN IP.

```
Starting networking.
Make sure to iterate over replies if you need connection alive management!
WAN IP = 8.8.8.8
Determining node type.
Node type = passive
```

**Comment by robertsdotpm** [comment]
The Net class queries external servers for the WAN IP if it isn't set manually. The reason why the Google IP is used in some of the tests is to avoid that happening for tests that don't do anything with the WAN IP (which is mostly all of them.)
