### ISSUE TITLE
All non critical features must be opt in.

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#54]
I would like storj to be secure by default and one part of getting that is making non critical features off by default as anything not activated cant be a security risk ...

Critical features for the network to work and that must be enabled by default are:

 * Core DHT rpc calls (stun, ping, find peers, store value, get value)
 * Relay messages

Everything else should be off by default and only added when needed. Most features require a message handler to be added so this is what I have been doing so far. See [here](https://github.com/Storj/storjnode/blob/develop/storjnode/network/messages/info.py#L150) where I explicitly enable responding to info requests.

Currently on by default?

 * handle unl requests?
 * bandwith tests?

@robertsdotpm can you check that the data transfer code and bandwidth test is off by default?

**Comment by robertsdotpm** [comment]
File transfers currently require a Boolean accept handler that describes the route / origin and returns true for a SYN message to be processed. I've changed the bandwidth test handlers and unl req handlers to be enabled manually and added this code to the tests.

Just to be safe: I'll also disable reverse connect in pyp2p by default as its a possible DoS vector and the current code doesn't directly use it. I might add something similar to a white list for TCP hole punching as that could potentially be abused as well.

**Comment by F483** [comment]
While they are not opt in, they are at least opt out via the config.
