### ISSUE TITLE
Logging statements not being executed

### ISSUE THREAD

**Issue by robertsdotpm** [Storj/storjnode#55]
It seems that when you run code with the unittest module debug statements don't seem to execute for other modules. I.e. the statements in node.py and bandwidth/test.py. I'm not sure why this is but it would be useful to have (not a critical problem)

python -m unittest tests.network.node.TestNode.test_network_monitor_service

**Comment by F483** [comment]
For unittests you need to use the --verbose flag to enable debug output and you must get the logger via [storjnode.log.getLogger](https://github.com/Storj/storjnode/blob/master/storjnode/log.py#L23).

This is the only solution I found where twisted doesn't spam the everything. All global loggers are silenced and then you get a child logger with the level given in the arguments, be default it is set to INFO, --verbose or --debug enable full log output and --quiet disables it.

**Comment by F483** [comment]
You must use the storj logger to have logging displayed, all global loggers are disabled by default.

```
>>> import storjnode
>>> log = storjnode.log.getLogger("example_logger")
>>> log.info("example info log")
>>> type(log)
logging.Logger
```

The log level controlled with the program arguments `--debug`, `--verbose`, `--quiet`.

The global logger can be enabled for debugging by setting the environment variable `STORJNODE_ENABLE_GLOBAL_LOGGER` to a non zero value.
