### ISSUE TITLE
Actually stop listening on port when stopping node.

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#58]
When a node is stopped it should properly disconnect form its port so it can be used again by other applications.

The node initially starts listening [here](https://github.com/Storj/storjnode/blob/develop/storjnode/network/node.py#L172) and should stop listening [here](https://github.com/Storj/storjnode/blob/develop/storjnode/network/server.py#L149).

**Comment by F483** [comment]
@ELQET feel free to take this if you wish.

**Comment by ELQET** [comment]
ok I take it
