### ISSUE TITLE
Use smarter algorithm to find next available predictable key when saving monitor results

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#59]
The shard id of the monitor results is saved at a predictable key in the DHT ("monitor_dataset_{NODE_ADDRESS}_{MONITOR_RESULT_NUMBER}").

Currently it finds the key by simply iterating beginning at zero and checking if a result was already saved, this does not scale.

To quickly find the next available it should probe for free slots with an exponential increase. Then use a binary search to find the first free slot between the found slot and zero.

https://github.com/Storj/storjnode/blob/develop/storjnode/network/monitor.py#L190

**Comment by F483** [comment]
@gordonwritescode @ELQET this is a good issues to get your fee wet with the DHT

**Comment by ELQET** [comment]
ok

**Comment by F483** [comment]
@ELQET you should talk to shawn about becoming a team member, that way I can assign or you can take the issue to prevent someone else doing overlapping work.

**Comment by ELQET** [comment]
I think I have not only get my feet but whole body wet with the DHT :) Because this dictionary like distributed hash table and kademlia style you implementing is awesome. It uses binary tree structure so binary search will be based on this. I hope you do it this way and I will try to use this advantage in favor of my implementation of binary search on this distributed hash table. Very interesting stuff though.

**Comment by F483** [comment]
Adding this here so I don't forget.
Confirm @ELQET change is correct https://github.com/ELQET/storjnode/blob/develop/storjnode/network/monitor.py#L304

**Comment by F483** [comment]
FYI @ELQET you can just make a pull request and if it needs work, just push the updates to your repository (the pull request will automatic update). That way another developer aside from me may check it and accept if I don't have time.

**Comment by F483** [comment]
@ELQET on first glance it does look ok. You will have to add a unit test to ensure this, I cannot accept non trivial code without tests.

**Comment by F483** [comment]
You might also want to consider creating a custom compare object like I did [here](https://github.com/Storj/dataserv-client/blob/master/dataserv_client/builder.py#L109) for another project. That way you can use the standard lib for the search and not reimplement a possibly buggy binary search.

**Comment by ELQET** [comment]
You are right, I will do it your way with bisect. Thank you for your time and advice. I appreciate it.
Also I implement unit test, I do it now so I can close this task. Thanks again

**Comment by F483** [comment]
The submitted code did not do what its supposed to, so I reverted it. The test was also incorrect so I added a corrected test.

It must pass this test https://github.com/Storj/storjnode/blob/develop/tests/network/node.py#L438

**Comment by F483** [comment]
Implemented as originally specified. https://github.com/Storj/storjnode/blob/develop/storjnode/network/monitor.py#L305

@ELQET next time should ask more questions as you clearly did not understand the issue. It did not behave correctly and it also read each slot which entirely defeated the purpose of the binary search.

@super3 did you accept [this pull request](https://github.com/Storj/storjnode/pull/84)? Or does @ELQET have commit access?

**Comment by ELQET** [comment]
I know what binary search does. And frankly I wasn't sure about my code. But I must say I ask somebody for review on SLACK. Nobody answered. You can look to history of dev. I din't aks specific person I asked everybody. But nobody answered.  Also I wrongly inspired by your code https://github.com/Storj/dataserv-client/blob/master/dataserv_client/builder.py#L109 But never mind... Shit happens :)
Sorry for trouble, my bad. I should ask more questions for sure.

**Comment by super3** [comment]
@F483 Gave @ELQET commit access because that is the only way we can assign issues. Normally we wait for a few pull before giving access. Next time I'll add new users with read only access.

@ELQET Pull requests are the best way to have the code reviewed. Lots of messages on Slack so things can get a bit lost. Good to specifically mention one of us if its time for review.
