### ISSUE TITLE
Cannot connect to a real IRC server, only local

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjnode#6]
subwolf commented 8 hours ago

Trying to connect to anything other than a local test IRC server, by modifying tests/network/test_connection.py

test_connects (tests.network.test_simultaneous_connect.TestSimultaneousConnect) ... Failed connecting to 127.0.0.1:6667 as tRdIHkGyhQnn /home/subwolf/storjnode/storjnode/network/service.py:113: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 50256)> _log.warning("Failed connecting to %s:%s as %s", host, port, nick) Couldn't connect to network! ERROR

Test server is 209.141.47.51

**Comment by littleskunk** [comment]
@F483 
The IRC server address should be set once. At the moment it is set in every unit test. I can do it if you like. My solution would be a config.py in storjnode/tests. Please give me that job :)

**Comment by F483** [comment]
Maybe this is an issue with your setup. I have been testing on other networks  (mostly quakenet) the whole time. I only added local tests because of Travis limitations.

**Comment by F483** [comment]
I haven't tried it with the servers you guys setup, but it shouldn't be a problem if you can connect with a normal IRC client.

**Comment by littleskunk** [comment]
As far as i understand subwolf (aka robin) wants to start the unit test with an other IRC Server but for that he would have to change more than 1 file.

https://github.com/Storj/storjnode/blob/develop/tests/network/test_connection.py#L6
https://github.com/Storj/storjnode/blob/develop/tests/network/test_simultaneous_connect.py#L7
etc.

**Comment by F483** [comment]
I tried that but it doesn't work with travis. For unit tests it's better to use a local one anyway, as it's the same and isolated every time.

**Comment by littleskunk** [comment]
Ok i have to agree. It would be a big problem if unit test run on the real IRC server later. Closed for now as user error.

**Comment by F483** [comment]
I will reopen this when I get to my pc. It makes sense to run the tests on a custom server to ensure it is setup correctly. I will add in environment variables to override the defaults for this.

**Comment by F483** [comment]
Tests now check an environment variable for the server to use.

`export STORJNODE_USE_RELAYNODE="irc.quakenet.org:6667"`
`python setup.py test`
