### ISSUE TITLE
Storjnode develop branch not compatible with dataserv-client develop branch

### ISSUE THREAD

**Issue by subwolf** [Storj/storjnode#97]
If you compare:

https://github.com/Storj/dataserv-client/blob/develop/dataserv_client/api.py#L84

and

https://github.com/Storj/storjnode/blob/develop/storjnode/config/__init__.py#L96

They are currently not compatible, the storjnode get command accepts one argument for get(), the dataserv-client get command sends two. Because both parts are tested individually - and one against the master branch of the pip requirements (and not develop), this doesn't show up in tests.

**Comment by F483** [comment]
DHT network and default config paths are completely devoiced between dataserv_client and storjnode, as well as python module paths.

Both clients are completely divorced and do not need to be compatible.
